### ISSUE TITLE
Agregar informacion a los datos publicados

### ISSUE THREAD

**Issue by DobleV55** [datos-justicia-argentina/Registro-Nacional-de-Sociedades#1]
Hola, existe la posiblidad de que se puedan agregar en una columna de los csv publicados el/los ID de actividad de las personas jurídicas?

**Comment by jsadi** [comment]
Hola Valentín, estamos consultando con el Registro, en breve te respondo. Saludos, Judith

**Comment by jsadi** [comment]
Hola Valentin, el registro está coordinando con Afip y otros organismos para incluir ese dato.
Saludos, Judith

**Comment by DobleV55** [comment]
a

**Comment by DobleV55** [comment]
Hola Judith, espero te encuentres bien!

Agradezco enormemente la respuesta rápida y positiva de tu parte, nos alegra que se este llevando a cabo esta modificación.

Este mensaje no es para presionar ni apurar estos cambios, pero me gustaria saber si existe alguna fecha planeada para esta integracion. De esta manera podre planear en el roadmap la integracion de este nuevo cambio. O si directamente vere los cambios realizados en la siguiente subida de Registro Nacional de Sociedades - 2024 semestre 2. 

http://datos.jus.gob.ar/dataset/registro-nacional-de-sociedades

Quedo atento a tu respuesta,
Saludos!

**Comment by jsadi** [comment]
Hola Valentín, entiendo tu urgencia. Ya derivamos la consulta al RNS y estamos esperando su respuesta. Todavía no sabemos si es factible incorporar este dato al dataset ni cuánto tiempo llevaría hacerlo.
Nosotros sólo publicamos las novedades que ellos nos remiten.
Copio este mail a la dirección de mail que publica el Registro en el portal para consultas de usuarios - ***@***.******@***.***> - para que reciban tus inquietudes directamente.
Saludos,


Judith Sadi
Programa Justicia Abierta
***@***.***
(011) 5300-4000 int. 76572
25 de mayo 350 6º CABA
Ministerio de Justicia


De: Valentin Vila ***@***.***
Enviado el: lunes, febrero 05, 2024 3:50 PM
Para: datos-justicia-argentina/Registro-Nacional-de-Sociedades
CC: Judith Violeta Sadi; State change
Asunto: Re: [datos-justicia-argentina/Registro-Nacional-de-Sociedades] Agregar informacion a los datos publicados (Issue #1)


Hola Judith, espero te encuentres bien!

Agradezco enormemente la respuesta rápida y positiva de tu parte, nos alegra que se este llevando a cabo esta modificación.

Este mensaje no es para presionar ni apurar estos cambios, pero me gustaria saber si existe alguna fecha planeada para esta integracion. De esta manera podre planear en el roadmap la integracion de este nuevo cambio. O si directamente vere los cambios realizados en la siguiente subida de Registro Nacional de Sociedades - 2024 semestre 2.

http://datos.jus.gob.ar/dataset/registro-nacional-de-sociedades

Quedo atento a tu respuesta,
Saludos!

**Comment by jsadi** [comment]
Estimados, buenos días.
Estamos ocupándonos de dar curso a dicha consulta, sin embargo no podemos estimar una fecha cierta para confirmar si se puede llevar a cabo dicho requerimiento dado que parte de los distintos equipos intervinientes se encuentran en receso por vacaciones.
Les estaremos informando a la brevedad en cuanto se produzcan novedades.

Saludos cordiales,

Dirección de los Registros Nacionales de Sociedades y del Registro Nacional de Concursos y Quiebras

________________________________
De: Judith Violeta Sadi
Enviado: lunes, 05 de febrero de 2024 04:21 p.m.
Para: datos-justicia-argentina/Registro-Nacional-de-Sociedades; datos-justicia-argentina/Registro-Nacional-de-Sociedades
CC: State change; Registro Nacional de Sociedades y Concursos y Quiebras
Asunto: RE: [datos-justicia-argentina/Registro-Nacional-de-Sociedades] Agregar informacion a los datos publicados (Issue #1)

Hola Valentín, entiendo tu urgencia. Ya derivamos la consulta al RNS y estamos esperando su respuesta. Todavía no sabemos si es factible incorporar este dato al dataset ni cuánto tiempo llevaría hacerlo.
Nosotros sólo publicamos las novedades que ellos nos remiten.
Copio este mail a la dirección de mail que publica el Registro en el portal para consultas de usuarios - ***@***.******@***.***> - para que reciban tus inquietudes directamente.
Saludos,


Judith Sadi
Programa Justicia Abierta
***@***.***
(011) 5300-4000 int. 76572
25 de mayo 350 6º CABA
Ministerio de Justicia


De: Valentin Vila ***@***.***
Enviado el: lunes, febrero 05, 2024 3:50 PM
Para: datos-justicia-argentina/Registro-Nacional-de-Sociedades
CC: Judith Violeta Sadi; State change
Asunto: Re: [datos-justicia-argentina/Registro-Nacional-de-Sociedades] Agregar informacion a los datos publicados (Issue #1)


Hola Judith, espero te encuentres bien!

Agradezco enormemente la respuesta rápida y positiva de tu parte, nos alegra que se este llevando a cabo esta modificación.

Este mensaje no es para presionar ni apurar estos cambios, pero me gustaria saber si existe alguna fecha planeada para esta integracion. De esta manera podre planear en el roadmap la integracion de este nuevo cambio. O si directamente vere los cambios realizados en la siguiente subida de Registro Nacional de Sociedades - 2024 semestre 2.

http://datos.jus.gob.ar/dataset/registro-nacional-de-sociedades

Quedo atento a tu respuesta,
Saludos!
